### ISSUE TITLE
Support json5?

### ISSUE THREAD

**Issue by WWQ1993** [jonkwheeler/tsconfig-replace-paths#2]
just like tsconfig.json supported json5

**Comment by jonkwheeler** [comment]
I'd have no problem with this at all

**Comment by trusktr** [comment]
This would be nice. It currently fails on projects with comments in tsconfig.json.

**Comment by jonkwheeler** [comment]
This feature was added actually. JSON5 is supported now. If you're seeing otherwise, open a new issue about it. But in my testing, it works.
