### ISSUE TITLE
Paths not replacing when running package as indicated in documentation

### ISSUE THREAD

**Issue by bradenmitchell** [jonkwheeler/tsconfig-replace-paths#25]
Firstly, thanks for picking up where `tscpaths` left off. I'm using `tsconfig-replace-paths` in my build script as described in the documentation, however no paths are being replaced. `tscpaths` replaces paths as expected at the moment.

I have a basic project setup with a `src` directory that contains a `config` and `utils` directory that are aliased to `@config` and `@utils` respectively.

Any insight into what might be going wrong here would be greatly appreciated.

### build script
`"build": "rimraf ./build && tsc -p tsconfig.json && tsconfig-replace-paths --project tsconfig.json --src ./src --out ./build -v"`

### tsconfig.json
```
{
  "compilerOptions": {
    "target": "es2021",
    "lib": ["es2021"],
    "jsx": "preserve",
    "experimentalDecorators": true,
    "allowJs": false,
    "outDir": "./build",
    "removeComments": true,
    "importHelpers": true,

    "module": "commonjs",
    "rootDir": "./src",
    "moduleResolution": "node",
    "baseUrl": "./src",
    "paths": {
      "@app": ["./app.ts"],
      "@config": ["./config/*", "./config"],
      "@utils": ["./utils/*", "./utils"]
    },

    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,

    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "allowUnreachableCode": false,

    "skipLibCheck": true
  }
}
```

### build output with `-v`
```
Using tsconfig: C:\Users\mitbl001\Desktop\erebus\server\tsconfig.json
Using flag --src
Using src: C:\Users\mitbl001\Desktop\erebus\server\src
Using flag --out
Using out: C:\Users\mitbl001\Desktop\erebus\server\build
baseUrl: ./src
rootDir: C:\Users\mitbl001\Desktop\erebus\server\src
outDir: C:\Users\mitbl001\Desktop\erebus\server\build
paths: {
  "@app": [
    "./app.ts"
  ],
  "@config": [
    "./config"
  ],
  "@utils": [
    "./utils"
  ]
}
basePath: C:\Users\mitbl001\Desktop\erebus\server\src
outPath: C:\Users\mitbl001\Desktop\erebus\server\build
aliases: [
  {
    "prefix": "@app",
    "aliasPaths": [
      "C:\\Users\\mitbl001\\Desktop\\erebus\\server\\src\\app.ts"
    ]
  },
  {
    "prefix": "@config",
    "aliasPaths": [
      "C:\\Users\\mitbl001\\Desktop\\erebus\\server\\src\\config"
    ]
  },
  {
    "prefix": "@utils",
    "aliasPaths": [
      "C:\\Users\\mitbl001\\Desktop\\erebus\\server\\src\\utils"
    ]
  }
]
Replaced 0 paths in 0 files
```

**Comment by jonkwheeler** [comment]
On phone...

Why are your paths absolute? They show the C drive and all that. They should be relative I believe. Should be relative to your project folder.

**Comment by kennethfreitas** [comment]
I have the exact problem, didn't replace anything. With the verbose flag, the path is also shown as absolute (Windows 10).

**Comment by bradenmitchell** [comment]
Interesting... I didn't notice that. I ran that on my work machine (which is heavily admin restricted) so I thought that might be a reason but if you're experiencing it as well maybe that isn't a contributing factor. I'll re-run it on my MacBook when I get a chance hopefully this week and report back.

**Comment by jonkwheeler** [comment]
Hey, I've got a newborn at home so I'm taking a bit of leave at the moment. Sorry I won't be super attentive to this in the super short term. Babies are a lot of work.

A few things to try though. Double up the paths in the tsconfig. I do this on my repos (and I can't remember why). I also don't specify specific files as a path. I'd do `@root/app` or `@/app` instead. Honestly, not telling you what do or change your coding style, I'm just trying to highlight differences between yours and mine.

Here's an example of mine: 
```
"paths": {
      "@components": ["./src/components"],
      "@components/*": ["./src/components/*"],
      "@root": ["./"],
      "@root/*": ["./*"],
      "@utils": ["./src/utilities"],
      "@utils/*": ["./src/utilities/*"],
      "@vars": ["./src/variables"],
      "@vars/*": ["./src/variables/*"]
}
```

I use `tsconfig-replace-paths` to compile all my packages which are TypeScript, including all the private repos I have for work and don't have any issues.

Here's 2 public examples though from my repos: 

- https://github.com/jonkwheeler/ScrollScene/blob/master/tsconfig.json#L27
- https://github.com/jonkwheeler/styled-velocity/blob/master/tsconfig.json#L27

**Comment by bradenmitchell** [comment]
Thanks @jonkwheeler - not a problem at all and congrats on the little one! I'll have a play around with those suggestions and check out the repos.

**Comment by jonkwheeler** [comment]
Closing for now. Let me know if you need to talk through it more.
