### ISSUE TITLE
Extraneous `../` in resolved paths?

### ISSUE THREAD

**Issue by vendethiel** [jonkwheeler/tsconfig-replace-paths#30]
Hi,

I'm trying to use tsconfig-replace-paths but the generated paths go back up one extra level.

My setup is as such:

```
tsconfig.json
shared/
    parser.ts
server/
    uses-parser.ts
    tsconfig.json (not interesting)
test-server/
    uses-parser.ts
    tsconfig.json
out/
    test-server/
        shared/
        server/
        test-server/
```

My global configuration contains
```json
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "@shared/*": [
        "shared/*"
      ],
      "*": [
        "node_modules/*"
      ]
    },
```

and then the `tsconfig.json` files in `server/` and `test-server/` are:
```json
{
  "extends": "../tsconfig.json",
  "include": [
    "."
  ]
}
```
(the only extra thing `test-server/tsconfig.json` contains is `noEmit: false` to generate code, because I need to run mocha on it and all the module that offer to run TS via mocha don't seem to work with my usecase).

Running this module properly finds files & replaces in them (I tried both with and without `-p test-server/tsconfig.json`):
```
$ npx tsconfig-replace-paths -s test-server -o out/test-server
Replaced 1 paths in 1 files
```

But the transformation is off by one level:
```typescript
import Parser from "@shared/parser";
// got changed to
import Parser from "../../shared/parser";
```
Which tries to find a module `out/shared/parse-assert` (instead of `out/test-server/shared/parse-assert`) and fails.

Not sure if it's because my setup is weird or because I missed an option, but I'd like to know how I can solve this.
Thanks!

**Comment by jonkwheeler** [comment]
I guess I'm unsure why you would want this. This package is for changing compiled files.

Here's an example input.

```
./src
  - index.ts
  - my-awesome-package.ts
```

Here's an example output.

```
./dist
  - index.js
  - index.d.ts
  - my-awesome-package.js
  - my-awesome-package.d.ts
```

Having the path back out of your dist folder won't work because those files need to be included for your package to work correctly.

Am I missing something?

**Comment by vendethiel** [comment]
> Am I missing something?

I need my files compiled to run mocha on it; like mentioned in the original message. Trying to use ts-mocha doesn't work because tsconfig-paths is broken, so I need to compile my code/tests to run my tests.

**Comment by jonkwheeler** [comment]
Closing for now. Feel free to push back. I believe your setup should just be altered?

Here is what a common setup looks like referencing your files.

```
tsconfig.json
src/
    shared/
        parser.ts
    server/
        uses-parser.ts
        tsconfig.json (not interesting)
    test-server/
        uses-parser.ts
        tsconfig.json
out/
    shared/
        parser.js
        parser.d.ts
    server/
        uses-parser.js
        uses-parser.d.ts
    test-server/
        uses-parser.js
        uses-parser.d.ts
```

**Comment by vendethiel** [comment]
You should probably specify in the README or something that the tool expects a specific directory structure (I don’t see a difference between my root or a src/ directory, and I don’t understand why it’s a problem)
