### ISSUE TITLE
the globby.sync cann't find the file path in windows

### ISSUE THREAD

**Issue by vcup** [jonkwheeler/tsconfig-replace-paths#42]
Hi, i have an node typescript esm project, work on linux with this tool.
but when i running in windows it will not handler any file.
i insert some logging code into `node_modules/tsconfig-replace-paths/dist/commonjs/index.js`,
finnally found the problem in globby.sync(), if the pattren path contained the windows path separator `\`, is always returun `[]`

https://github.com/jonkwheeler/tsconfig-replace-paths/blob/69d11595a439f744d44f7010ec386ee54ed27732/src/index.ts#L208-L212

i already soveled this issue, can i open an pull request?

**Comment by vcup** [comment]
@jonkwheeler

**Comment by jonkwheeler** [comment]
Yes, apparently it doesn't work on Windows right now. I don't have a Windows machine to test this.

Someone submitted a PR with a potential fix, however then it broke on Mac (Unix), so I did not merge it.
