### ISSUE TITLE
TypeError: outPath.replaceAll is not a function for 0.0.14

### ISSUE THREAD

**Issue by mjx20045912** [jonkwheeler/tsconfig-replace-paths#45]
I got error for 0.0.14: TypeError: outPath.replaceAll is not a function. And my ts-config like: 

```
 "lib": [
      "es6",
      "es2016.array.include",
      "dom",
      "ES2021.String"
    ],
```

**Comment by jonkwheeler** [comment]
Do either of these example configs help?

https://github.com/jonkwheeler/tsconfig-replace-paths/tree/master/examples
